from __future__ import annotations

from decimal import Decimal

USDT_SYMBOL = "USDT"
BSC_NETWORK = "BSC"
BSC_CHAIN_ID = 56

MONEY_PRECISION = 18
MONEY_SCALE = Decimal("0.000000000000000001")

DEFAULT_REFERRAL_LEVEL = 1
MAX_REFERRAL_LEVEL = 3

MAX_WITHDRAWAL_AMOUNT = Decimal(1000000)
MIN_WITHDRAWAL_AMOUNT = Decimal(1)

TRANSACTION_REFERENCE_MAX_LENGTH = 128
WALLET_ADDRESS_LENGTH = 42
TX_HASH_LENGTH = 66
